EasyCart/EasyCart/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns =[
    path('admin/', admin.site.urls),
    path('',include('homescreen.urls')),
    path('cartdataapp/',include('cartdataapp.urls')),
    path('search/',include('search_app.urls')),
    path('cart/',include('cart.urls')),
    path('accounts/',include('accounts.urls')),

]
urlpatterns=urlpatterns+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

EasyCart/accounts/urls.py
from django.urls import path
from . import views
app_name='accounts'
urlpatterns = [
    path('register',views.register,name='register'),
    path('login',views.login,name='login'),
    path('logout', views.logout, name='logout')

]

EasyCart/cart/urls.py
from django.conf.urls import url
from django.urls import path
from .import views
app_name = 'cart'
urlpatterns=[
    path('',views.cart_detail,name='cart_detail'),
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/',views.full_remove,name='full_remove'),

]

EasyCart/cartdataapp/urls.py
from django.urls import path
from cartdataapp import views
app_name='cartdataapp'

urlpatterns = [
    path('',views.allproduct,name='allproduct'),
    path('<slug:c_slug>/',views.allproduct,name='product_by_category'),
    path('<slug:c_slug>/<slug:p_slug>/',views.acpdetail,name='acpdetail'),
]

EasyCart/search_app/urls.py
from django.urls import path
from .import views
app_name="search_app"
urlpatterns=[
    path('',views.SearchResult,name='SearchResult'),
]

EasyCart/cart/models.py
from django.db import models
from cartdataapp.models import Product
# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)
    class Meta:
        db_table='Cart'
        ordering=['date_added']
    def __str__(self):
        return self.cart_id

class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart= models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)

    class Meta:
        db_table='CartItem'

    def sub_total(self):
        return self.product.price*self.quantity
    def __str__(self):
        return self.product

EasyCart/cart/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from cartdataapp .models import Product
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.
def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart


def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(cart_id=_cart_id(request))
        cart.save()
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock :
            cart_item.quantity+=1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(product=product,cart=cart,quantity=1)
        cart_item.save()
    return redirect('cart:cart_detail')


def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))

        cart_items=CartItem.objects.filter(cart=cart,active=True)

        for cart_item in cart_items:
            total+=(cart_item.product.price * cart_item.quantity)
            counter+=cart_item.quantity
    except ObjectDoesNotExist:
        pass

    return render(request,'cart.html',dict(cart_item=cart_items,total=total,counter=counter))



def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity>1:
        cart_item.quantity-=1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

def full_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

EasyCart/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <meta name="decription" content="{% block metadescription %} {%endblock%}">
    <title>{% block title %} {% endblock %}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" >
    <link href="{% static 'css/custom.css' %}" rel="stylesheet" >
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
</head>
<body>
<div>
    {% include 'header.html' %}
    {% include 'nav.html' %}
    {% block content %}
    {% endblock %}
</div>
{% include 'footer.html' %}
<script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

EasyCart/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
        Cart-shop your favorate !!!
{% endblock %}
{% block content %}
{% if not cart_item %}
    <div>
        <div class="text=center">
            <h1 class="text_center my_title">Your shop cart is Empty</h1><br>
            <p class="text-center">Please click<a href="{% url 'cartdataapp:allproduct' %}">Here</a></p>
        </div>
    </div>


{% else %}
    <div>
        <div class="text-center"><br>
            <h1 class="text-center my_title" style="font-family:monospace">Your Shopping Cart</h1><br>
        </div>
    </div>
    <div class="row mx-auto">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_custom_table">
                <thead class="my_custom_thead">
                <tr>
                    <th colspan="5">Your Items</th>
                </tr>
                </thead>
                <tbody>
                {% for cart_it in cart_item %}
                <tr>
                    <td>
                        <a href="cart_it.product.get_absolute_url"><img src={{cart_it.product.image.url}} class="float-left rounded custom_image" style="height:130px;width:130px;"></a>
                    </td>
                    <td class="text-left">
                        {{cart_it.product.name}}<br>
                        SKU:{{cart_it.product.id}}<br>
                        Unit price:{{cart_it.product.price}}
                        Quantity:{{cart_it.quantity}} * ${{cart_it.product.price}}

                    </td>
                    <td>${{cart_it.sub_total}}</td>

                    {% if cart_it.quantity < cart_it.product.stock %}
                        <td>
                            <a href="{% url 'cart:add_cart' cart_it.product.id %}" class="custom_a"><i class="fas fa-plus custom_icon"></i></a>&nbsp
                            <a href="{% url 'cart:cart_remove' cart_it.product.id %}" ><i class="fas fa-minus custom-icon"></i></a>&nbsp
                            <a href="{% url 'cart:full_remove' cart_it.product.id %}" class="custom-icon>"><i class="fas fa-trash-alt custom-icon"></i></a>

                        </td>
                    {% else %}
                        <td>
                            &nbsp<a href="{% url 'cart:cart_remove' cart_it.product.id %}" class="custom_a"><i class="fas fa-minus custom_icon"></i></a>&nbsp
                            <a href="{% url 'cart:full_remove' cart_it.product.id %}" class="custom-icon"><i class="fas fa-trash-alt custom-icon"></i></a>
                        </td>
                    {% endif %}
                </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
                <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                    <table class="table my_custom_table">
                        <thead class="my_custom_thead">
                        <tr>
                            <th>
                                Checkout
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>
                                Please review your shopping cart items before proceeding with the order payment
                            </td>
                        </tr>
                        <tr>
                        <td class="text-left">
                            Your total is <strong>$ {{total}}</strong>
                        </td>
                        </tr>
                        </tbody>
                    </table>

                    <div class="mx-auto">
                        <a href="{% url 'cartdataapp:allproduct' %}" class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a>
                    </div>
                </div>
    </div>
{% endif %}
{% endblock %}

EasyCart/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {% if category %}
        {{category.name}}-Easy-cart
    {% else %}
        See our collections-Easy-cart
    {% endif %}
{% endblock %}

{% block content %}
    <div>
    {% if category %}
        <img src="{{category.image.url}}" alt="{{category.name}}"style="height:650px;width:1350px">
        <h1 class="text-center" style="font-family:monospace;">{{category.name}}</h1>
        <p class="text-justify" style="text-align:justify;">{{category.desc}}</p>

    {% else %}
        <div>
        <center><img src="{% static 'image/lapcart.jpg' %}" alt="error occured" style="width:1330px;height:599px;"></center>
        </div>
        <div>
            <div>
            <h3 class="text-center" style="font-family:monospace;"><b>OUR PRODUCTS COLLECTIONS</b></h3>
            <p style="text-align:justify;">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc. .</p>
    </div>
        </div>
    {% endif %}
    </div>
</div>
<div class="container">
    <div class="row max-auto">
        {% for product in products.object_list %}
            <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
                <div class="card text-center" style="width: 18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top my-image" src="{{product.image.url}}" style="width:250px;height:250px;" alt="{{product.name}}"> </a>
            <div class="card-body">
                 <h4>{{product.name}}</h4>
                <p>${{product.price}}</p>
                </div>
                </div>
         </div>
    {% endfor %}

    </div>

    <div class="mx-auto">
        <div class="text-center">
        {% for pg in products.paginator.page_range %}
        <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} activate {% endif %}">{{pg}}</a>
        {% endfor %}

    </div>
        </div>
{% endblock %}
         </div>

EasyCart/templates/footer.html
<footer>
    <div class="text-center p-3" style="background-color: rgb(216, 227, 136);">
   <b>©Easy Cart:</b>
    <b><p class="text-dark">Explore Your Purchasing With Our Collections </p></b>
  </div>
  <!-- Copyright -->
</footer>

<!--<div>-->
<!--    <p class="text-center">&copy;Avodha Training.All Rights Reserved.</p>-->
<!--</div>-->

EasyCart/templates/header.html
<!--{% load static %}-->
<!--<div>-->
<!--    <center>-->
<!--        <img src="{%static 'image/l.png' %}" alt="This is logo of EasyCart">-->
<!--    </center>-->
<!--</div>-->

EasyCart/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>login</title>
</head>
<body>
<form action="login" method="post">
    {% csrf_token %}
    <div align="center"><h1 style="color:green"><b><u>Login</u></b></h1></div>
    <div align="center">
    <input type="text" name="username" placeholder="Username"><br>
    <input type="text" name="password" placeholder="Password"><br>
    <input type="submit" value="Login">
    </div>
</form>
</body>
</html>

EasyCart/templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
<!--    <a class="navbar-brand" href="#">Navbar</a>-->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar navbar-expand-sm">
      <h3 style="color:#4287f5;padding-right:70px;font-family:Fantasy;"><b>EASY CART</b> <i class="fab fa-opencart" style="color:#0377fc"></i></h3><br>
    </div>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'cartdataapp:allproduct' %}">Home</a>
        </li>
        {% if item_count > 0 %}
          <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fas fa-shopping-cart">{{item_count}}</i></a>
        </li>
        {% endif %}



        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Category
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'cartdataapp:allproduct' %}">All Products</a></li>
                {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
                {% endfor %}
            <li><hr class="dropdown-divider"></li>
<!--            <li><a class="dropdown-item" href="#">Something else here</a></li>-->

          </ul>
        </li>
          {% if user.is_authenticated %}
            <li><b>Hai {{user.username}}</b></li>

            <li class="nav-item">
             <a class="nav-link" href="{% url 'accounts:logout' %}">LOGOUT</a>
            </li>
          {% else %}
            <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:login' %}">LOGIN</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:register' %}">REGISTER</a>
          </li>
          {% endif %}
      </ul>
        <form class="d-flex" action="{% url 'search_app:SearchResult' %}" method="get">
          {% csrf_token %}
          <input class="form-control me-2"  type="text" placeholder="Search" aria-label="Search" name="q">
          <button class="btn btn-outline-success" type="submit"><i class="fas fa-search"></i></button>
        </form>
    </div>
  </div>
</nav>

<!--&lt;!&ndash;<nav>&ndash;&gt;-->
<!--&lt;!&ndash;    <ul>&ndash;&gt;-->
<!--&lt;!&ndash;        <li><a href="{% url 'cartdataapp:allproduct' %}">All Products</a></li>&ndash;&gt;-->
<!--&lt;!&ndash;        {% for cat in links %}&ndash;&gt;-->
<!--&lt;!&ndash;            <li><a href="{{cat.get_url}}">{{cat.name}}</a> </li>&ndash;&gt;-->
<!--&lt;!&ndash;        {% endfor %}&ndash;&gt;-->
<!--&lt;!&ndash;        <li>Your Cart</li>&ndash;&gt;-->
<!--&lt;!&ndash;    </ul>&ndash;&gt;-->
<!--&lt;!&ndash;</nav>&ndash;&gt;-->

EasyCart/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
{{pro.name}}
{% endblock %}
{% block content %}
<!--<div class="row my_prod_row_class">-->
<!--    <div class="mx-auto">-->
<!--            <a href="{% url 'cartdataapp:allproduct' %}">Home</a> |  <a href="{{pro.category.get_url}}">{{pro.name}}</a>-->
<!--        </div>-->
<!--    </div>-->
<!--<div class="container">-->
<!--<div class="row">-->
<!--    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-cenetr">-->
<!--        <div style="min-width:8rem;">-->

<!--        <img src="{{pro.image.url}}" alt="{{pro.name}}">-->
<!--    </div>-->
<!--</div>-->
<!--    </div>-->
<!--</div>-->

<!--<div class="col-12 col-sm-12 col-md-12 col-lg-6">-->
<!--    <div>-->
<!--        <h3>{{pro.name}}</h3>-->
<!--        <h3>${{pro.price}}</h3>-->
<!--        <p>{{pro.desc}}</p>-->
<!--    </div>-->
<!--</div>-->
<!--{% if pro.stock <= 0 %}-->
<!--    <h1 style="color:red">Out Of Stock</h1>-->
<!--{% else %}-->
<!--    <a href="">Add To Cart</a>-->

<!--{% endif %}-->
<!--{% endblock %}-->



<div class="row my_prod_row_class">
    <div class="mx-auto">
          <a href="{% url 'cartdataapp:allproduct' %}">Home</a> |  <a href="{{pro.category.get_url}}">{{pro.name}}</a>
    </div>
</div>

<div class="container"><br>
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-cenetr">
            <div style="min-width:8rem;">

            </div>
        </div>
<div class="col-12 col-sm-12 col-md-12 col-lg-6">
    <div>
       <h1 class="my_prod_title">{{pro.name}}</h1>
                <p class="my_title">{{pro.price}}</p>
               <b><p class="text-justify my_prod_text">{{pro.desc}}</p></b>
                    {% if pro.stock <= 0 %}
                        <h1 style="color:red">Out Of Stock</h1>
                    {% else %}
                        <a href="">Add To Cart</a>

                    {% endif %}
    </div>
</div>

    </div>
</div>
{% endblock %}

EasyCart/templates/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="register" method="post" >
    {% csrf_token %}
    <div align="center"><h1 style="color:green"><b><u>Registration</u></b></h1></div>
    <div align="center">
    <input type="text" name="username" placeholder="Username"><br>
    <input type="text" name="firstname" placeholder="Firstname"><br>
    <input type="text" name="lastname" placeholder="Lastname"><br>
    <input type="email" name="email" placeholder="Email"><br>
    <input type="password" name="password" placeholder="Password"><br>
    <input type="password" name="cpassword" placeholder="Confirm password"><br>
    <input type="submit" value="Registration">
    </div>
</form>

<div align="center">
    {% for message in messages %}
    <h3 style="color:red">{{message}}</h3>
    {% endfor %}
</div>

</body>
</html>

EasyCart/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {% if category %}
        {{category.name}}-shop -cart
    {% else %}
        see our collections-shop cart
    {% endif %}
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text">You have Searched for: {{query}}</p>
</div>
<div class="container">
    <div class="row max-auto" >
        {% for product in products %}
            <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
                <div class="card text-center" style="width: 18rem;">
                    <a href="{{product.get_url}}"><img class="card-img-top my_img" src="{{product.image.url}}" style="width:250px;height:250px;" alt="{{product.name}}"> </a>
                    <div class="card-body" >
                        <h4>{{product.name}}</h4>
                        <p>${{product.price}}</p>
                    </div>
                </div>
            </div>
        {% empty %}
            <div class="row mx-auto">
            <p class="text-center my_search_text">0 results found</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

EasyCart/templates/testing.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
{{pro.name}}
{% endblock %}
{% block content %}
<!--<div class="row my_prod_row_class">-->
<!--    <div class="mx-auto">-->
<!--          <a href="{% url 'cartdataapp:allproduct' %}">Home</a> |  <a href="{{pro.category.get_url}}">{{pro.name}}</a>-->
<!--    </div>-->
<!--</div>-->

<div class="container"><br>
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-cenetr">
            <div style="min-width:8rem;">
                <img src="{{pro.image.url}}" style="height:350px;width:350px;">
            </div>
        </div>
<div class="col-12 col-sm-12 col-md-12 col-lg-6">
    <div>
       <h1 class="my_prod_title" style="font-family:monospace;">{{pro.name}}</h1>
      <p class="my_title"><b>{{pro.price}}</b></p>
               <h3 style="font-family:monospace;"> <b>PRODUCT DESCRIPTION</b></h3>
                <p style="text-align:justify;">{{pro.desc}}</p>
                    {% if pro.stock <= 0 %}
                        <h1 style="color:red;font-family:monospace">!!!! Out Of Stock !!!!</h1>
                    {% else %}
                        <a class="btn btn-secondary" href="{% url 'cart:add_cart' pro.id %}">Add To Cart</a>

                    {% endif %}
    </div>
</div>

    </div>
</div>
{% endblock %}